""" Defining constant variables """
BASE_URL = "https://www.goodreads.com"
LOGIN_URL = BASE_URL + "/user/sign_in"
URL = BASE_URL + "/shelf/show/non-fiction"
PAGE_URL_TEXT = "?page="
REPORTS_PATH = "./reports/"
